#!/usr/bin/env bash

echo "vimifying..."

current_pwd=$(pwd)
echo $current_pwd
#	check if there is a .vimrc
#	if there is, rename it with .old
#	cp the current vmrc with the new one
#	do same with .vim folder

update_vimrc() {

	# CHECK FOR AND INSTALL ~/.vimrc FILE
	if [ -f ~/.vimrc ]; then
		echo ".vimrc file already exists."
		echo " Renaming existing .vimrc file as .vimrc-old"
		mv ~/.vimrc ~/.vimrc-old
	else
		echo ".vimrc file does not exist."
	fi

	echo "Copying vimify .vimrc file to home directory"
	cp .vimrc ~/.vimrc
}

update_vim_folder() {
	# CHECK FOR AND INSTALL .vim FOLDER
	# .vim folder contains bundles colors and autoload script.
	
	if [ -d ~/.vim ]; then
		echo ".vim folder already exists"
		echo "Renaming .vim folder "
		rm -rf ~/.vim-old
		mv  ~/.vim ~/.vim-old
	else
		echo "no .vim folder found"
	fi

	echo "Copying vimify .vim folder to ~/.vim"
	cp -r .vim ~/.vim
}

update_vim() {
	echo -ne "\n" | sudo add-apt-repository ppa:jonathonf/vim
	sudo apt update
	echo "Y" | sudo apt install vim

}

install_dependencies() {
	# INSTALL DEPENDENCIES
	echo "Creating UltiSnips ftdetect simlink"
	mkdir -p ~/.vim/ftdetect/
	ln -s ~/.vim/ultisnips/ftdetect/* ~/.vim/ftdetect/

	echo "Installing dependencies for YouCompleteMe autocomplete"
	yes Y | sudo apt-get install build-essential cmake python3-dev python-dev
	
	echo "Compiling YouCompleteMe with semantic support for C-family"

	cd ~
	curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.33.11/install.sh | bash
	source ~/.bashrc
	export NVM_DIR="$HOME/.nvm"
	[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
	[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion
	nvm install --lts

	cd ~/.vim/bundle/YouCompleteMe
	
	# install with c language completed, and javascript/typescript completer
	python3 install.py --clang-completer --ts-completer
}

case $1 in
	install)
		update_vimrc
		update_vim_folder
		install_dependencies
	;;

	update_all)
		update_vimrc
		update_vim_folder
	;;
	update_pkgs)
		update_vim_folder
	;;
	update_conf)
		update_vimrc
	;;

	install_all)
		update_vim
		update_vimrc
		update_vim_folder
		install_dependencies
	;;
	install_dependencies)
		install_dependencies	
	;;
	replace_vim_program)
		update_vim
	;;
	*)
		echo "Vimify"
		echo ""
		echo "Usage: vimify [command]"
		echo ""
		echo "  install               if unsure, run this. If vim is out of date run update_vim_program"
		echo "                        will update .vim .vimrc and grab apt dependencies, and run installers"
		echo ""
		echo "  update_all		        install dependencies for pkgs, and update  .vim and .vimrc"
		echo "  update_pkgs           copy over .vim folder from vimify to ~/.vim"
		echo "  update_conf           override ~/.vimrc file with vimify's .vimrc"
		echo ""
		echo "  install_all           run install and update_vim_program"
		echo "  install_dependencies	install dependencies only"
		echo "  replace_vim_program   for Ubuntu systems, deletes old vim, downloads source, and recompiles"
		echo ""

	;;

esac


